apiVersion: v1
kind: Service
metadata:
  name: sample-node-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sample-node-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
